#!/usr/bin/env bash
# Create custom 404 page

ERROR_COPY="Ceci n'est pas une page"

# Update and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create the custom 404 page
echo "$ERROR_COPY" | sudo tee /var/www/html/custom_404.html > /dev/null

# Update the nginx default site configuration
sudo sed -i '/^\s*server_name.*/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/^\s*location.*/i \        error_page 404 /custom_404.html;' /etc/nginx/sites-available/default

# Restart nginx to apply changes
sudo systemctl restart nginx
