#!/usr/bin/env bash
# Create custom 404 page
ERROR_COPY="Ceci n'est pas une page"

# Update package lists
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Create custom 404 page
echo "$ERROR_COPY" | sudo tee /var/www/html/custom_404.html > /dev/null

# Backup the default Nginx configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Configure Nginx to use the custom 404 page and add the redirect rule
sudo sed -i '/^\s*server_name.*/a \        error_page 404 /custom_404.html;\n        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Ensure the 'location' block exists before adding the custom 404 page configuration
sudo sed -i '/^\s*location \/ {/a \        try_files $uri $uri/ =404;' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart

