#!/usr/bin/env bash
# Ignore SC2154 for shellcheck
# shellcheck disable=SC2154

# Update and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Get the hostname
HOSTNAME=$(hostname)

# Add the custom header configuration
sudo sed -i '/^\s*server_name.*/a \        add_header X-Served-By '"$HOSTNAME"';' /etc/nginx/sites-available/default

# Restart nginx to apply changes
sudo systemctl restart nginx
