#!/usr/bin/env bash
# configures to run and listen on port 80

# Ensure Nginx is installed
sudo apt-get update
sudo apt-get install -y nginx

# Update Nginx configuration to listen on port 80
sudo sed -i "s/listen 80 default_server;/listen 80 default_server;/" /etc/nginx/sites-available/default
sudo sed -i "s/listen \[::\]:80 default_server;/listen \[::\]:80 default_server;/" /etc/nginx/sites-available/default

sudo systemctl restart nginx

