#!/usr/bin/env bash
#this code prints all the files in the dir

for file in *; do
    if [[ ! $file == .* && $file == *-* ]]
    then
        name_after_dash="${file}"
        echo "$name_after_dash"
    fi
done

